version: '3.3'
    
services:
  app:
    environment:
        - PORT=8000
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
        - .:/app
    ports:
        - '8000:8000'
